perfomance: Create a new getP selector for each translate instance
Tiqa/redux-polyglot pull request #89
Opened 2018-01-24 00:08 UTC by lneves12

**Problematic**
Atm there is a global getP selector for all the translate hoc components. As soon as a translate hoc is added to a page with custom options, for instance the option polyglotScope, it will mess with all the other existent translates as the reselect selector only keep cache of one element and we are passing these options as selector props.

**Solution**
Create a new getP selector for each translate, so each instance keeps their own cache instead of conflicting with all the other translates.

Any other ideas of how to tackle this issue?

@satazor

2018-01-24 00:56 UTC, guillaumearm commented
Hi @lneves12 

Congratulations, you will be the 7th contributor on `redux-polyglot` project.
Thanks for helping this library growing.

I thinks it's a good approach.
selector factories is most of the time a good solution in this kind of situation.

----------

## Some steps before merging : 

### 1. Tests

You need to write some tests to highlight this issue.

### 2. Discuss

We will wait for the opinion of @JalilArfaoui  and @satazor. 
(@nemosupremo, @0xClpz and @jvincent42 are welcome too)

For instance, maybe we need to talk about the name of the function.
`createGetP` or `makeGetP` ?

### 3. Documentation

You need to write documentation about this.
I know, the `redux-polyglot` documentation is not very pretty, but we need to keep it up to date.

2018-01-24 01:28 UTC, satazor requested changes

2018-01-24 01:28 UTC, satazor commented on src/selectors.js
> +const getPolyglot = () => createSelector(
Factories for selectors usually start with `create`, in this case it should be `createGetPolyglot`.
While these selectors are internal, I would rename them.

2018-01-24 01:29 UTC, satazor commented
LGTM, I made the review with just one little thing regarding the naming.

This PR needs tests though.

2018-01-24 01:43 UTC, lneves12 commented
Thanks for the fast review :)

I can add some tests and normalize the naming of the selector factories as soon I have some time. Probably during tomorrow

2018-01-24 17:59 UTC, lneves12 commented
Just added some tests for my changes and normalised the selectors factories as @satazor suggested.

I ran my test before my changes and it went from red->green.

Let me know if you need something else from me in this pull request :)

2018-01-24 22:13 UTC, satazor commented
I think this is good to be merged @guillaumearm

2018-01-26 15:52 UTC, satazor commented
Bump @guillaumearm

2018-01-26 17:14 UTC, guillaumearm commented
Sorry for the late, it was a difficult week for me.
I will merge this PR and release a `0.6.3` version tonight.

2018-01-26 18:05 UTC, lneves12 commented
Awesome. Thanks @guillaumearm

2018-01-26 21:54 UTC, merged