Lodash assign for react native support
Tiqa/redux-polyglot pull request #99
Opened 2018-04-19 18:43 UTC by rjerue

Love this library for use of Polyglot with web development. I'm working on a react native project with shared items to a react.js project and wanted to use this library for i18n. However, Object.assign in React-Native does not allow for enumerable keys to be prototypes on objects, and they are for Polygots.

The solution is to change the {... p, ...} (which is Object.assign) to use Lodash's assign instead.

2018-04-19 22:48 UTC, guillaumearm requested changes
Hi, thanks for contributing to `redux-polyglot`.

Since our CI is broken, we need to run tests before push.
At this time, tests are broken, please fix them.

In addition, please install `npm@5` and run a `npm install` in order to update `package-lock.json`

2018-04-19 22:48 UTC, guillaumearm commented on src/selectors.js
> +            return assign(p, t, tc, tt, tu, tm);
from https://lodash.com/docs/4.17.5#assign : 
> This method mutates object

You need to `assign({}, ...)`.
Anyway, `t`, `tc`, `tt`, `tu` and `tm` are functions.

The correct implementation is next : 
```js
return assign({}, p, t, tc, tt, tu, tm);
```

2018-04-20 00:46 UTC, rjerue commented
I'll look into fixing the best tests... As of now, Jest isn't detecting that anything is found.

2018-04-20 05:30 UTC, rjerue commented
Changes made, passes all unit tests now. Still works in my app too.

Hope other React-Native users find use for this.

2018-04-20 11:01 UTC, guillaumearm approved these changes

2018-04-20 11:03 UTC, merged

2018-04-20 11:09 UTC, guillaumearm commented
Nice work @rjerue, You are now part of [redux-polyglot contributors](https://github.com/Tiqa/redux-polyglot/graphs/contributors).

Anyway, I just released `redux-polyglot@0.6.5` on `latest` npm dist-tag.